// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-operations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
var OPERATIONS = [
  {
    id: "apply_layout",
    tab: "Layout",
    name: "Copy Page Layout",
    description: "Copies page size, headers, footers and their content from the Source document to the Target document.",
    options: ["pageSize", "header", "footer", "copyHeaderFooterContent", "deleteEmptyParagraphs"]
  },
  {
    id: "copy_styles",
    tab: "Layout",
    name: "Copy Styles",
    description: "Copies paragraph styles from Source to Target.",
    options: []
  },
  {
    id: "format_helper",
    tab: "Format",
    name: "Format Helper",
    description: "Detects Italic/Bold/Bold+Italic text in the Source and adds review comments in the Target (author: Format Assist).",
    options: []
  },
  {
    id: "clean_meps",
    tab: "Format",
    name: "Clean the MEPS Up",
    description: "Removes text using the selected MEPS fonts from the Target document.",
    options: ["mepsBookmanWTS", "mepsBookmanUniversal"]
  },
  {
    id: "replace_key_phrases",
    tab: "ADP",
    name: "Replace Key Phrases",
    description: "Uses an Excel dictionary (Column A to Column B) to replace phrases in the Target document.",
    options: ["excludeComments", "includeHeaderFooter"]
  },
  {
    id: "transfer_dp_comments",
    tab: "ADP",
    name: "Transfer DP Comments",
    description: 'Copies comments by author "Digital Publishing" from Source to the matching paragraph in Target.',
    options: ["findIdentifier", "replaceWith", "excludeIt"]
  },
  {
    id: "detect_missing_sections",
    tab: "ADP",
    name: "Detect Missing Sections",
    description: "Reports headings present in Source but missing from Target.",
    options: []
  }
];
var list_operations_default = defineTool({
  name: "list_operations",
  title: "List SDTD operations",
  description: "List the document operations SDTD supports, with their tab, description and configurable option keys.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(OPERATIONS, null, 2) }],
    structuredContent: { operations: OPERATIONS }
  })
});

// src/lib/mcp/tools/list-presets.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-presets.ts
var list_presets_default = defineTool2({
  name: "list_presets",
  title: "List saved presets",
  description: "List the signed-in user's saved SDTD presets, optionally filtered by operation id.",
  inputSchema: {
    tool: z.string().optional().describe("Optional operation id, e.g. apply_layout.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tool }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("presets").select("id, name, tool, options, notes, created_at, updated_at").order("updated_at", { ascending: false });
    if (tool) query = query.eq("tool", tool);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { presets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-preset.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var save_preset_default = defineTool3({
  name: "save_preset",
  title: "Save a preset",
  description: "Create a saved SDTD preset for the signed-in user: a named set of options for one operation.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Preset name."),
    tool: z2.string().trim().min(1).describe("Operation id from list_operations."),
    options: z2.record(z2.union([z2.string(), z2.boolean(), z2.number()])).optional().describe("Option keys and values for the operation."),
    notes: z2.string().optional().describe("Optional free-text notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, tool, options, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError("Could not resolve the signed-in user.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("presets").insert({ user_id: userId, name, tool, options: options ?? {}, notes: notes ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { preset: data }
    };
  }
});

// src/lib/mcp/tools/delete-preset.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var delete_preset_default = defineTool4({
  name: "delete_preset",
  title: "Delete a preset",
  description: "Permanently delete one of the signed-in user's saved SDTD presets by id.",
  inputSchema: {
    id: z3.string().trim().min(1).describe("Preset id returned by list_presets.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("presets").delete().eq("id", id).select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: `No preset found with id ${id}.` }], isError: true };
    }
    return { content: [{ type: "text", text: `Deleted preset ${id}.` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "oxuniijwmbapbftrdjfo";
var mcp_default = defineMcp({
  name: "sdtd",
  title: "SDTD",
  version: "0.1.0",
  instructions: "Tools for SDTD, a Word add-in that syncs a Source document to a Target document. Use `list_operations` to see the supported document operations and their option keys, and `list_presets` / `save_preset` / `delete_preset` to manage the signed-in user's saved option presets.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_operations_default, list_presets_default, save_preset_default, delete_preset_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
